sudo: required
dist: xenial
language: node_js
node_js:
  - "6.3"
addons:
  firefox: "latest"
services:
  - xvfb
before_script:
  - cd js
  - npm install grunt-cli -g
  - npm install
#  - export DISPLAY=:99.0
#  - sh -e /etc/init.d/xvfb start
#  - sleep 3
script: grunt test
