sudo: required
dist: xenial
language: node_js
node_js:
  - "6.3"
addons:
  firefox: "latest"
services:
  - xvfb
before_script:
  - cd js
  - npm install grunt-cli -g
  - npm install
script: grunt test
